[build]
# Use all cores for parallel compilation
rustflags = ["-C", "target-cpu=native"]

[unstable]
# Enable nightly-only cargo features
mtime-on-use = true
build-std = ["std", "core", "alloc"]

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"