name: Documentation

on:
  push:
    branches: [main]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
        
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          
      - name: Generate Docs
        run: |
          # Build the standard Rust docs
          cargo doc --no-deps --document-private-items
          
          # Create a docs directory structure
          mkdir -p target/doc/lmopt_rs/docs/concepts
          mkdir -p target/doc/lmopt_rs/docs/examples
          
          # Copy the markdown files to the docs directory
          cp docs/getting_started.md target/doc/lmopt_rs/docs/
          cp docs/concepts/*.md target/doc/lmopt_rs/docs/concepts/
          cp docs/examples/*.md target/doc/lmopt_rs/docs/examples/
          
          # Copy README.md as index.html for GH Pages
          cp README.md target/doc/index.md
          
          # Create .nojekyll file to disable Jekyll processing
          touch target/doc/.nojekyll
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./target/doc

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2